name: BluestarCraft
version: '${project.version}'
main: me.lanzhi.bluestarcraft.BluestarCraftPlugin
api-version: 1.17
commands:
  bluestarcraft:
    permission: BluestarCraft.command
    aliases:
      - bscraft
permissions:
  BluestarCraft.*:
    children:
      BluestarCraft.command:
        default: op
depend:
  - NBTAPI
  - BluestarAPI