shaped:
  recipe1:
    shape:
      - '  a'
      - ' aaa'
      - 'aaaaa'
      - ' aaa'
      - '  a'
    result: 'minecraft:diamond_block'
    amount: 2
    ingredient:
      a: 'minecraft:diamond' #也可以直接写diamond
shapeless:
  recipe2:
    ingredient:
      diamond: 20
    result: 'minecraft:diamond_block'
    amount: 5